services:

  redis:
    image: redis:8.0.0
    volumes:
      - redis_data:/data
 
  api:
    image: ghcr.io/serverlessworkflow/synapse/api
    environment:
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      SYNAPSE_DASHBOARD_SERVE: 'true'
      SYNAPSE_API_AUTH_TOKEN_FILE: /app/tokens.yaml
      SYNAPSE_API_JWT_AUTHORITY: http://api:8080
      SYNAPSE_API_CLOUD_EVENTS_ENDPOINT: https://webhook.site/a4aff725-0711-48b2-a9d2-5d1b806d04d0
    volumes:
      - ./config/tokens.yaml:/app/tokens.yaml
    ports:
      - 8080:8080
    depends_on:
      - redis

  operator:
    image: ghcr.io/serverlessworkflow/synapse/operator
    environment:
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      SYNAPSE_OPERATOR_NAMESPACE: default
      SYNAPSE_OPERATOR_NAME: operator-1
      SYNAPSE_RUNNER_API: http://api:8080
      SYNAPSE_RUNNER_LIFECYCLE_EVENTS: 'true'
      SYNAPSE_RUNNER_CONTAINER_PLATFORM: docker
      SYNAPSE_RUNTIME_DOCKER_SECRETS_DIRECTORY: C:\Users\User\.synapse\secrets
      DOCKER_HOST: unix:///var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    depends_on:
      - redis

  correlator:
    image: ghcr.io/serverlessworkflow/synapse/correlator
    environment:
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      SYNAPSE_CORRELATOR_NAMESPACE: default
      SYNAPSE_CORRELATOR_NAME: correlator-1
    ports:
      - 8081:8080
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: synapse